# https://taskfile.dev
version: '3'
vars:
  IMG: sgaunet/postgis:latest

tasks:
  default:
    desc: "List all tasks"
    cmds: 
      - task -a

  build:
    desc: "Build the docker image"
    cmds:
      - docker build --no-cache . -t sgaunet/postgis:latest
      - docker push sgaunet/postgis:latest
  
  run:
    desc: "Run the docker image"
    dir: deploy
    cmds:
      - docker compose up -d

