---
services:
  postgres-server:
    image: sgaunet/postgis:latest
    ports:
    - 5432:5432
    stop_grace_period: 1m
    environment:
    - POSTGRES_USER=postgres
    - POSTGRES_PASS=password
    - POSTGRES_DBNAME=mydb
    - POSTGRES_MULTIPLE_EXTENSIONS=postgis,postgis_topology,pgcrypto
    - PASSWORD_AUTHENTICATION=md5
    - ARCHIVE_MODE=off
    - ALLOW_IP_RANGE=0.0.0.0/0
    healthcheck:
      test: ["CMD", "pg_isready -U postgres"]
      interval: 3s
      timeout: 5s
      retries: 5
    volumes:
    - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d