name: publish docker image
on: push

jobs:
  publish-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the postgis Docker image
        run: |
          docker build . -t ghcr.io/sgaunet/postgis:latest
          docker push       ghcr.io/sgaunet/postgis:latest
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"
          if [ ! -z "${{ github.ref_name }}" ]; then
            echo "Tag name from github.ref_name: ${{  github.ref_name }}"
            docker build . -t ghcr.io/sgaunet/postgis:${{  github.ref_name }}
            docker push       ghcr.io/sgaunet/postgis:${{  github.ref_name }}
          fi